export var E_JSON_RPC_ERROR;
(function (E_JSON_RPC_ERROR) {
    E_JSON_RPC_ERROR[E_JSON_RPC_ERROR["PARSE_ERROR"] = -32700] = "PARSE_ERROR";
    E_JSON_RPC_ERROR[E_JSON_RPC_ERROR["INVALID_REQUEST"] = -32600] = "INVALID_REQUEST";
    E_JSON_RPC_ERROR[E_JSON_RPC_ERROR["METHOD_NOT_FOUND"] = -32601] = "METHOD_NOT_FOUND";
    E_JSON_RPC_ERROR[E_JSON_RPC_ERROR["INVALID_PARAMS"] = -32602] = "INVALID_PARAMS";
    E_JSON_RPC_ERROR[E_JSON_RPC_ERROR["INTERNAL_JSON_RPC_ERROR"] = -32603] = "INTERNAL_JSON_RPC_ERROR";
    E_JSON_RPC_ERROR[E_JSON_RPC_ERROR["INTERNAL_SERVER_ERROR"] = -32000] = "INTERNAL_SERVER_ERROR";
})(E_JSON_RPC_ERROR || (E_JSON_RPC_ERROR = {}));
//# sourceMappingURL=jsonrpc-api.js.map